### ISSUE TITLE
cell vertex / edge coordinates

### ISSUE THREAD

**Issue by johnny-smitherson** [yuyttenhove/meshless_voro#5] opened 2024-09-20 11:30 UTC
Hello,

I'm looking at this crate for a voro++ replacement. Performance is as advertised.

But I can't seem to work out how to get the actual coordinates of the cell vertices from the library, just the centroids + volumes for cells, and centroid+ normal + area for the faces.

In voro++ binding crate `voro_rs` these operations are supported:
- [list cell vertices(in local space)](https://docs.rs/voro_rs/latest/voro_rs/cell/trait.VoroCell.html#tymethod.vertices_local)
- [face vertices](https://docs.rs/voro_rs/latest/voro_rs/cell/trait.VoroCell.html#tymethod.face_vertices)

These coordinates are then used in generating 3D mesh objects and loading them into OpenGL for visualization.

Am I missing some detail/feature from the library, or is extracting vertex information not supported in the library?

Is there some kind of post-processing one can do on the data returned by the library to obtain the coordinates for the cell vertices?

Thanks,

**Comment by yuyttenhove** [comment] 2024-09-20 13:06
Hi, 

Thanks for the interest in this crate. 

While this library, like voro++, uses a cell-based construction algorithm, the [algorithm](https://inria.hal.science/hal-01927559/file/voroGPU.pdf) itself and representation in memory of the Voronoi cells is different. Hence, this crate does not aim to be a direct replacement for voro++. What you want might still be possible with some (small) additions, though. 

Currently, the cell/face vertices are not stored in the final `Voronoi`/`VoronoiCell`struct, as they would take up quite a bit of space. However, they are stored in the [`VoronoiIntegrator`](https://docs.rs/meshless_voronoi/0.6.1/meshless_voronoi/struct.VoronoiIntegrator.html)/[`ConvexCell`](https://docs.rs/meshless_voronoi/0.6.1/meshless_voronoi/struct.ConvexCell.html) struct. 

We could very easily add a public function to `ConvexCell` that returns all the vertices of that cell. Extending the public API of `ConvexCell` might be a good idea in any case. 

Due to how `ConvexCell` is stored (see [this paper](https://inria.hal.science/hal-01927559/file/voroGPU.pdf) for details), getting the (indices) of the vertices of all the faces would be a little more work but still possible.

**Comment by yuyttenhove** [comment] 2024-09-20 15:09
I made the vertices in `ConvexCell` public and added a method to get the vertices of a given face. Note that the method to get the vertices of a face is not particularly efficient, though...

I also added methods to `VoronoiIntegrator` to get a reference to a specific `ConvexCell` and an iterator over all `ConvexCell`s.

If this suffices for your needs, I can publish a new version on crates.io

**Comment by johnny-smitherson** [comment] 2024-09-30 01:33
Thanks for the help with the implementation!

I can now match up the returned values (within float tolerance) with voro_rs/voro++ for all of the following:
- cell centroid, volume
- cell face count
- cell vertex list


I have some trouble extracting the face vertex indexes using the new `fn get_face_vertices` - it sometimes gives empty list back when given ints in `0..(voronoi_cell.face_count())`. When trying to give it IDs above that, it seems to find more faces - do I have to check all possible ids for faces (from `Voronoi::faces()` combined with `Voronoi::cell_face_connections()`) instead of checking 0..face_count ? 

In other words, how do i get the [`0..6` interval](https://github.com/yuyttenhove/meshless_voro/commit/49a9152111b21c13a125c8a90c1ee44776f8f49f#diff-7edb454ba6da04af3153d5f0d2ede5e0f75324aa0ed9882cf00051559b839ca0R563) for an example with lots of random points?


---


I might be holding it wrong, but there also seems to be a little double computation issue with the interface? Let me explain:

- `ConvexCell::get_face_vertices(self, face_idx)` requires caller to know the total number of faces for the cell
- total number of faces only available in `VoronoiCell::face_count()`
- getting from `VoronoiIntegrator/ConvexCell` to `Voronoi/VoronoiCell` can be done only with `voronoi_integrator.into()` which consumes the argument, or by running `Voronoi::build()` on same arguments

This results in running `VoronoiIntegrator::build()` twice on the same data. This slows down processing by some 33%

I think this could be avoided by either adding `#[derive(Clone)]` on `VoronoiIntegrator`, or by implementing `From<&VoronoiIntegrator>`, or some other fn, which leaves the original in place, so i can zip through both types of cells at the same time.


Here is my benchmark on 4000 random points, default features

```
Voronoi::build: 19.9344ms
VoronoiIntegrator::build: 8.9469ms
extract face vertex: 18.5732ms

total meshless_voro: 52.7209ms
```


With multi-threaded disabled (to compare with voro_rs) the recompute is even more rough:

```
Voronoi::build: 77.7103ms
VoronoiIntegrator::build: 64.8869ms
extract face vertex: 15.3077ms

total meshless_voro: 161.1865ms

total voro_rs/++: 134.9803ms
```

---

Here is the snippet i'm using to extract all the stuff


https://gist.github.com/johnny-smitherson/873e412b5ba1dda0b95a8aed73654ab3

If interested i can publish a full exe crate to reproduce the face vertex issue

**Comment by yuyttenhove** [comment] 2024-09-30 15:08
Hi, the API wasn't really usable in that state indeed. Some of the clipping planes in a `ConvexCell` might not correspond to a face anymore, which is why some of your vertex lists were empty. But the bigger issue was that the `face_idx` passed into the `get_face_vertices` functions referred to an index in the `HalfSpace`s list of that `ConvexCell` and hence did not correlate to the faces of a finalized `VoronoiCell`.

I now made the following changes:
- added a new state `WithFaces`  to `ConvexCells` in which there are methods available to get the number of faces, indices of the vertices of a given face (in the `vertices` list of the corresponding `ConvexCell`), the number of vertices of a face etc.
- added a method to `VoronoiIntegrator` to swicht to the `WithFaces` state for the `ConvexCells`
- made the computation of the face vertices more efficient
- made a method of `VoronoiIntegrator` to build the `VoronoiCell`s without dropping the `VoronoiIntegrator` part of the public api
- added `#derive(Clone)` as suggested 
- change the `From` implementation to `From<&VoronoiIntegrator>` as suggested

Feel free to suggest more changes!

Finally I'm wondering which info from the `Voronoi` struct do you actually need? Do you actually need to construct it?

**Comment by johnny-smitherson** [comment] 2024-10-01 00:14
It works perfectly

Only issue left was visibility of the marker structs causing 

```error: type `meshless_voronoi::voronoi::convex_cell::WithoutFaces` is private``` 

when calling `convex_cell.with_faces()` 

https://github.com/johnny-smitherson/meshless_voro/commit/644f6647a90856e989f6bb1c9058d90653f26d84

here is the new run times single-threaded

```
VoronoiIntegrator::build: 70.9299ms    
Voronoi::from(&_voronoi_integrator): 37.0328ms    
extract face vertex: 21.221ms    
MESHLESS VORO: 132.506ms
VORO RS: 133.8703ms    
```

> Finally I'm wondering which info from the Voronoi struct do you actually need? 

Yes I'll be using the volume and possibly face areas - through I can probably get off with some rougher approximations. Thanks for the tip!

**Comment by yuyttenhove** [comment] 2024-10-01 09:57
Hi, yes indeed, my bad. The latest commit fixes that.

I also changed the way `Voronoi::from<VoronoiIntegrator<WithFaces>>` works to better utilize the available information of the faces in that case. This improves performance a bit (especially if you have to compute the face vertices anyway). On my machine, I get with your setup (single threaded, 4000 generators):
```
VoronoiIntegrator::build: 87.472682ms
Voronoi::from(&_voronoi_integrator): 44.139502ms
VoronoiIntegrator::with_faces: 15.190936ms
extract raw info: 7.034071ms
Voronoi::from(&_voronoi_integrator) -- with faces: 17.674233ms
```
And with multithreading:
```
VoronoiIntegrator::build: 15.971561ms
Voronoi::from(&_voronoi_integrator): 7.950227ms
With faces: 2.380702ms
extract raw info: 7.338488ms
Voronoi::from(&_voronoi_integrator) -- with faces: 5.458097ms
```

**Comment by yuyttenhove** [comment] 2024-10-01 14:06
If these changes satisfy your needs, I will push a new version to `crates.io`

**Comment by johnny-smitherson** [comment] 2024-10-01 14:33
After moving the `.with_faces()` up from cell to integrator, and then using `Voironoi::from(&integrator_with_faces)`, i'm seeing some cells come back with negative `voronoi_cell.volume()` but correct absolute value.

If you want you can use this to check results against `voro_rs` library (one function generates the same VCellRaw struct you have in the tests, the other one compares 2 sets of results by matching the IDs)

https://gist.github.com/johnny-smitherson/3c17a65c867854e3b083efedf574c74e

**Comment by johnny-smitherson** [comment] 2024-10-01 14:44
Can also confirm the performance improvement of `Voronoi::from<VoronoiIntegrator<WithFaces>>` vs  `Voronoi::from<VoronoiIntegrator<WithoutFaces>>` 

and that only the new faster version produces negative volumes - the one without faces doesn't

Apologize in advance for the `as f32` in the test code above - i think i'll keep all the voronoi stuff in f64 and do the conversion downstream


--- 

also check the centroids that come back from `voronoi_cell.centroid()`, are different if the faster `Voronoi::from` is used

**Comment by yuyttenhove** [comment] 2024-10-01 20:02
Ah, right, my bad! I actually noticed that issue during testing, but just fixed the signs in the test to check if my other changes were working as intended, and then forgot to fix the issue before pushing...

It was just the winding of the face vertices that was in the wrong direction. 

Should be fixed now on the latest version.
I also checked the centroids, to be sure, and they also match (up to floating point round-off errors, of course).

Thanks again for the testing and feedback!

**Comment by johnny-smitherson** [comment] 2024-10-01 22:39
yes works great thanks
<img width="336" alt="Screenshot 2024-10-02 013903" src="https://github.com/user-attachments/assets/6f24ecbb-a017-49d4-8f85-c8fe88bf69d0">

**Comment by yuyttenhove** [comment] 2024-10-02 08:24
Awesome!

Off-topic: are you doing that visualization with something you built yourself? Is it available somewhere?

**Comment by johnny-smitherson** [comment] 2024-10-02 12:09
It's just a mix and match of the bevy engine samples

- https://bevyengine.org/examples/gizmos/3d-gizmos/
- https://bevyengine.org/examples/3d-rendering/3d-shapes/

Here is the code: https://github.com/johnny-smitherson/geometry_demo

If you take out the `voro_rs` references, and if you use the "ibig" or "malachite" backends for this crate, you can also compile the demo on web assembly and have a live demo (with github pages) similar to the bevy website 

For a demo in this repo you probably only want this part

https://github.com/johnny-smitherson/geometry_demo/blob/a474139eda7e4574c9e7d65aae5c4444e39f4ebe/src/display.rs#L118-L156

**Comment by yuyttenhove** [comment] 2024-10-02 14:30
I have published a new version on crates.io containing the changes discussed here.

**Closed as completed by yuyttenhove** 2024-10-02 14:30 UTC
